=== Sedarius-1/xml/WarhammerRepo.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.xD.com/WarhammerRepo"
    xmlns="http://www.xD.com/WarhammerRepo"
    xmlns:xd="http://www.xD.com/WarhammerRepo"
    xmlns:xn="http://www.xD.com/Author"
    elementFormDefault="qualified"
>
    <xsd:import
        namespace="http://www.xD.com/Author"
        schemaLocation="Author.xsd"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    />

    <xsd:element name="Main" type="xd:mainType"/>
    <xsd:complexType name="mainType">
        <xsd:sequence>
            <xsd:element name="author" type="xn:authorType"/>
            <xsd:element name="warhammerRepo" type="warhammerRepoType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="warhammerRepoType">
        <xsd:sequence>
            <xsd:element name="army" type="armyType" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="armyType">
        <xsd:sequence>
            <xsd:element name="armyData" type="armyDataType"/>
            <xsd:element name="unit" type="unitType" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="armyId" type="xd:id"/>
    </xsd:complexType>

    <xsd:complexType name="armyDataType">
        <xsd:sequence>
            <xsd:element name="name" type="xd:name"/>
            <xsd:element name="allegiance" type="xd:allegiance"/>
            <xsd:element name="description" type="xd:description"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="miniatureType">
        <xsd:sequence>
            <xsd:element name="name" type="xd:name"/>
            <xsd:element name="assemblyDate" type="xsd:date"/>
            <xsd:element name="paintDate" type="xsd:date"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="unitType">
        <xsd:sequence>
            <xsd:element name="unitData" type="unitDataType"/>
            <xsd:element name="miniature" type="miniatureType" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="unitDataTypeNoAttr">
        <xsd:sequence>
            <xsd:element name="name" type="xd:name"/>
            <xsd:element name="movement" type="xd:movementValue"/>
            <xsd:element name="WS" type="xd:statsValue"/>
            <xsd:element name="BS" type="xd:statsValue"/>
            <xsd:element name="S" type="xd:statsValue"/>
            <xsd:element name="T" type="xd:statsValue"/>
            <xsd:element name="Ld" type="xd:statsValue"/>
            <xsd:element name="Save" type="xd:saveValue"/>
            <xsd:element name="pointCost" type="xd:pointValue"/>
            <xsd:element name="role" type="xd:Role"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="unitDataType">
        <xsd:simpleContent>
            <xsd:extension base="unitDataTypeNoAttr">
                <xsd:attribute name="compulsory" type="xsd:boolean"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:simpleType name="movementValue">
        <xsd:restriction base="xsd:float">
            <xsd:minInclusive value="0.0"/>
            <xsd:maxInclusive value="24.0"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="statsValue">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="1"/>
            <xsd:maxInclusive value="16"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="saveValue">
        <xsd:restriction base="xsd:float">
            <xsd:minInclusive value="2"/>
            <xsd:maxInclusive value="6"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="pointValue">
        <xsd:restriction base="xsd:float">
            <xsd:minInclusive value="1"/>
            <xsd:maxInclusive value="1500"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="allegiance">
        <xsd:union>
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="Loyal"/>
                    <xsd:enumeration value="Traitor"/>
                </xsd:restriction>
            </xsd:simpleType>
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="Horusian"/>
                    <xsd:enumeration value="Imperial"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:union>
    </xsd:simpleType>

    <xsd:simpleType name="Role">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Troops"/>
            <xsd:enumeration value="Elites"/>
            <xsd:enumeration value="Heavy Support"/>
            <xsd:enumeration value="Fast Attack"/>
            <xsd:enumeration value="Lord of War"/>
            <xsd:enumeration value="HQ"/>
            <xsd:enumeration value="Primarch"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="name">
        <xsd:restriction base="xsd:NMTOKEN">
            <xsd:minLength value="1"/>
            <xsd:maxLength value="25"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="id">
        <xsd:restriction base="xsd:NMTOKEN">
            <xsd:minLength value="1"/>
            <xsd:maxLength value="3"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="description">
        <xsd:restriction base="xsd:NMTOKEN">
            <xsd:minLength value="1"/>
            <xsd:maxLength value="512"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== Sedarius-1/xml/Zadanie2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="Zadanie2.css"?>


<xd:Main
    xmlns:xd="http://www.xD.com/WarhammerRepo"
    xmlns:xn="http://www.xD.com/Author"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.xD.com/WarhammerRepo WarhammerRepo.xsd"
>
<xd:author>
    <xn:title>Author</xn:title>
    <xn:name>Jakub</xn:name>
    <xn:surname>Kalinowski</xn:surname>
    <xn:index>242413</xn:index>
</xd:author>
<xd:warhammerRepo>
    <xd:army>
        <xd:armyData>
            <xd:name>Ultramarines</xd:name>
            <xd:allegiance>Loyal</xd:allegiance>
            <xd:description>UwU</xd:description>
        </xd:armyData>
        <xd:unit>
            <xd:unitData compulsory="true">
                <xd:name>Tactical Squad Alpha</xd:name>
                <xd:movement>6.5</xd:movement>
                <xd:WS>4</xd:WS>
                <xd:BS>4</xd:BS>
                <xd:S>4</xd:S>
                <xd:T>4</xd:T>
                <xd:Ld>8</xd:Ld>
                <xd:Save>3</xd:Save>
                <xd:pointCost>100</xd:pointCost>
                <xd:role>Troops</xd:role>
            </xd:unitData>
            <xd:miniature>
                <xd:name>Alpha1</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Alpha2</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Alpha3</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Alpha4</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Alpha5</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Alpha6</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Alpha7</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Alpha8</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Alpha9</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Alpha10</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
        </xd:unit>
        <xd:unit>
            <xd:unitData compulsory="false">
                <xd:name>Tactical Squad Beta</xd:name>
                <xd:movement>6.5</xd:movement>
                <xd:WS>4</xd:WS>
                <xd:BS>4</xd:BS>
                <xd:S>4</xd:S>
                <xd:T>4</xd:T>
                <xd:Ld>8</xd:Ld>
                <xd:Save>3</xd:Save>
                <xd:pointCost>100</xd:pointCost>
                <xd:role>Troops</xd:role>
            </xd:unitData>
            <xd:miniature>
                <xd:name>Beta1</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Beta2</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Beta3</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Beta4</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Beta5</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Beta6</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Beta7</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Beta8</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Beta9</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
            <xd:miniature>
                <xd:name>Beta10</xd:name>
                <xd:assemblyDate>2022-02-12</xd:assemblyDate>
                <xd:paintDate>2022-02-12</xd:paintDate>
            </xd:miniature>
        </xd:unit>
    </xd:army>
</xd:warhammerRepo>
</xd:Main>
